version: '2'
services:
  server:
    restart: always
    image: tavily-mcp-sse:latest
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/build/.env
    command: ["sh", "-c", "cd /app/build && node index.js"]
    # environment:
    #   - PORT=3000
    #   - TAVILY_API_KEY=''
